sudo: required
dist: xenial
language: cpp
env: VERBOSE=1

addons:
  apt:
    packages:
    # Core
      - build-essential
      - libvulkan-dev
    # Modules
      - libasound2-dev
      - libxi-dev

cache:
  directories:
    - pmk # Avoid downloading premake everytime

env:
    - CONFIGURATION=dbg
    - CONFIGURATION=dev
    - CONFIGURATION=rls

script: ./run.sh build ${CONFIGURATION}

os:
  - linux
  - windows

compiler:
  - gcc
  - clang

git:
  depth: 1
  quiet: true
